# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      srcDirectory: ./src

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'

    - name: Build
      run: go build
      working-directory: ${{env.srcDirectory}}

    - name: Test
      run: go test -json > testresults.json
      working-directory: ${{env.srcDirectory}}

    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: ${{env.srcDirectory}}/testresults.json
        retention-days: 7
